### ISSUE TITLE
Cannot find module '@babel/compat-data/corejs3-shipped-proposals' in WSL2

### ISSUE THREAD

**Issue by BryantShepherd** [chrisvfritz/vue-enterprise-boilerplate#204]
Hi, I recently installed WSL2 and tried to build this project on it, but this error keeps popping up. I used a fresh install of Ubuntu-20.04 from Microsoft Store. It ran perfectly on Windows though.

```sh
# Install all dependencies
yarn
# Run start script
node _start.js
# Run dev server
yarn dev --open
```

Here's the error messages.
```sh
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/src/main.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/node_modules/@babel/preset-env/lib/index.js
- /home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/node_modules/@vue/babel-preset-app/index.js
- /home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/node_modules/@vue/cli-plugin-babel/preset.js
- /home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/node_modules/@babel/core/lib/config/files/plugins.js
- /home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/node_modules/@babel/core/lib/config/files/index.js
- /home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/node_modules/@babel/core/lib/index.js
- /home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/node_modules/@vue/cli-plugin-babel/index.js
- /home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/node_modules/@vue/cli-service/lib/Service.js
- /home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/node_modules/@vue/cli-service/bin/vue-cli-service.js (While processing: "/home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/node_modules/@vue/cli-plugin-babel/preset.js")
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/anhlt/Coding/other/cloned_repos/vue-enterprise-boilerplate/node_modules/@babel/preset-env/lib/index.js:29:44)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)

 @ multi (webpack)-dev-server/client?http://172.20.23.79:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by BryantShepherd** [comment]
Removing `yarn.lock` and `node_modules`, then reinstall all dependencies using `yarn install` did solve the problem.
