### ISSUE TITLE
Vuetify integration

### ISSUE THREAD

**Issue by rodwin** [chrisvfritz/vue-enterprise-boilerplate#36]
Hi
Not an issue but rather a question.

Do you have an idea why the test returns this error

` dashboard git:(master) ✗ git commit -m "added donut chart"
 > running pre-commit hook: PRE_COMMIT=true lint-staged
 ❯ Running tasks for *.{js,jsx}
   ✔ eslint --fix
   ✔ prettier --write
   ✔ git add
   ✖ jest --bail --findRelatedTests
     →   at <anonymous>
 ✔ Running tasks for *.json
 ❯ Running tasks for *.vue
   ✔ eslint --fix
   ✔ stylelint --fix
   ✔ prettier --write
   ✔ git add
   ✖ jest --no-cache --bail --findRelatedTests
     →   at <anonymous>
 ↓ Running tasks for *.scss [skipped]
   → No staged files match *.scss
 ↓ Running tasks for *.md [skipped]
   → No staged files match *.md
 ↓ Running tasks for *.{png,jpeg,jpg,gif,svg} [skipped]
   → No staged files match *.{png,jpeg,jpg,gif,svg}
✖ jest --bail --findRelatedTests found some errors. Please fix them and try committing again.

             FAIL  src/router/views/home.unit.js
● Console

  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-content> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-jumbotron> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-flex> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-divider> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)

  ● @views/home › renders an element

  expect(string).toContain(value)

  Expected string:
    "Welcome to the site Lorem ipsum dolor sit amet, pri veniam forensibus id. Vis maluisset molestiae id, ad semper lobortis cum. At impetus detraxit incorrupte usu, repudiare assueverit ex eum, ne nam essent vocent admodum. "
  To contain value:
    "Home Page"

       8 |   it('renders an element', () => {
       9 |     const { element } = mountShallowView(Home)
    > 10 |     expect(element.textContent).toContain('Home Page')
      11 |   })
      12 | })
      13 |

      at Object.<anonymous> (src/router/views/home.unit.js:10:33)

Test Suites: 1 failed, 1 of 5 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        1.963s
Ran all test suites related to files matching /\/home\/rodwin\/Code\/tkl_ads\/dashboard\/src\/components\/DonutChart.unit.js|\/home\/rodwin\/Code\/tkl_ads\/dashboard\/src\/components\/DonutChart.js/i.
events.js:112
    throw er; // Unhandled 'error' event
    ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
  at process.target.send (internal/child_process.js:596:16)
  at reportSuccess (/home/rodwin/Code/tkl_ads/dashboard/node_modules/jest-worker/build/child.js:57:11)
  at <anonymous>
✖ jest --no-cache --bail --findRelatedTests found some errors. Please fix them and try committing again.

[vue-jest]: Sass, Less and PostCSS are not currently compiled by vue-jest

 FAIL  src/router/views/login.unit.js
● Console

  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-content> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-flex> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-card> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-toolbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-toolbar-title> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-spacer> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-tooltip> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-btn> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-card-text> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-form> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-text-field> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-text-field> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-card-actions> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-spacer> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-btn> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-content> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-flex> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-card> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-toolbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-toolbar-title> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-spacer> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-tooltip> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-btn> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-card-text> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-form> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-text-field> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-text-field> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-card-actions> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-spacer> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)
  console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Unknown custom element: <v-btn> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      (found in <Root>)

  ● @views/login › displays an error after failed login`

Thanks in advance.

**Comment by chrisvfritz** [comment]
Hm, it looks like it's complaining that a component hasn't been registered. Could you provide a diff or link to the project source?
