### ISSUE TITLE
error: Unexpected console statement

### ISSUE THREAD

**Issue by stuta** [chrisvfritz/vue-enterprise-boilerplate#47]
Clean install. Then yarn, yarn e2e.

```
error: Unexpected console statement (no-console) at src/components/_base-link.vue:44:18:
error: Unexpected console statement (no-console) at src/components/_base-link.vue:52:18:
...
```

**Comment by chrisvfritz** [comment]
This was related to [this vue-cli issue](https://github.com/vuejs/vue-cli/issues/1313) which has since been fixed, so those warnings should no longer appear.
